[package]
name = "tailwind"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Kelley"]
description = "Tailwind CSS engine implemented in Rust"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
